In [428]:
import os
import pandas as pd
import re
import numpy
from sklearn.metrics.pairwise import cosine_similarity

books=pd.read_csv("C:\\Users\\kp\\Pictures\\Assignments\\Recommendation system\\books.csv",encoding='latin1',header=0)
books=books.drop(['Unnamed: 0','users[, 1]'],axis=1)
books.columns=["Title","Author",'Publisher','Ratings']

def eliminate_missing_values(dataframe):

    dataframe.fillna('NA',inplace=True)
    dataframe.drop(dataframe[dataframe['Title']=='NA'].index,inplace=True)
    dataframe.drop(dataframe[dataframe['Author']=='NA'].index,inplace=True)
    dataframe.drop(dataframe[dataframe['Publisher']=='NA'].index,inplace=True)
        
    return dataframe

books=eliminate_missing_values(books)

kp=[]

for record in books['Title']:
    if ('http:' in record):
        temp=re.split(';',record)
        http_list=[i for i in range(0,len(temp)) if "http" in temp[i]]
        start=http_list[0]
        end=http_list[-1]
        kp=kp+temp[start:end]
    else:
        pass
for record in books['Author']:
    if ('http:' in record):
        temp=re.split(';',record)
        http_list=[i for i in range(0,len(temp)) if "http" in temp[i]]
        start=http_list[0]
        end=http_list[-1]
        kp=kp+temp[start:end]
    else:
        pass   
for record in books['Publisher']:
    if ('http:' in record):
        temp=re.split(';',record)
        http_list=[i for i in range(0,len(temp)) if "http" in temp[i]]
        start=http_list[0]
        end=http_list[-1]
        kp=kp+temp[start:end]
    else:
        pass
list_lists=[]

kp=[substring for substring in kp if( ('http:'not in substring) and (re.findall('^[0-9]',substring) not in [['0'],['1'],['2'],['3'],['4'],['5'],['6'],['7'],['8'],['9']]))]

In [429]:
#indexx=[i for i in range(0,len(kp)) if("The Road to El Dorado: Junior Novelization (Road to El Dorado)" in kp[i])]
#kp[9100:9103]

#Remove unwanted entries from the list
indexes = [336,337,800,801,1168,1169,1476,1477,2624, 2625,3220,3221,3222,3223,3224,4218,4219,4898,4899,4900,4901,4902,4903,
           4907,4908,4909,4910,4911,5890,5891,6117,6118,6398,6399,6409,6410,6600,6601,6602,6603,6604,6605,6606,6607,6608,6609,
           6610,6611,6612,6613,7958,7959,8269,8270,8355,8356,8840,8841,9100,9101]

for index in sorted(indexes, reverse=True):
    del kp[index]
    
for i in range(0,len(kp),3):
    list_lists.append(list(kp[i:(i+3)]))
    
df=pd.DataFrame(list_lists,columns =["Title","Author",'Publisher'])
df['Ratings']=0

def remove_unwanted_records(record):
    if ('http:' in record):
        record='NA'
        return record
    else:
        return record

books['Title']=books['Title'].apply(remove_unwanted_records)
books['Author']=books['Author'].apply(remove_unwanted_records)
books['Publisher']=books['Publisher'].apply(remove_unwanted_records)
books=eliminate_missing_values(books)

In [430]:
modified_books=pd.concat([books,df],ignore_index=True)
modified_books['Author']=modified_books['Author'].str.lower()
modified_books['Publisher']=modified_books['Publisher'].str.lower()
modified_books.drop_duplicates(subset ="Title",keep = 'first', inplace = True)

In [431]:
vectorizer_df=pd.get_dummies(data=modified_books, columns=['Author', 'Publisher'])
vectorizer_df

,Title,Ratings,Author_a first book,Author_a warlock in whitby (whitby series),Author_a'lelia bundles,Author_a. a. attanasio,Author_a. a. milne,Author_a. c. bhaktivedanta swami prabhupada,Author_a. c. crispin,Author_a. c. doyle,...,Publisher_you might as well laugh : because crying will only smear your mascara,Publisher_ywam publishing,Publisher_zebra books,Publisher_zebra/pinnacle books,Publisher_zenobia press,Publisher_znanje,Publisher_zondervan,Publisher_zondervan (j),Publisher_zondervan publishing company,Publisher_zondervan publishing house
0,Classical Mythology,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Clara Callan,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Decision in Normandy,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Flu: The Story of the Great Influenza Pandemic...,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,The Mummies of Urumchi,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8359,"The Rodale Herb Book: How to Use, Grow, and Bu...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8360,"Dinosaur Data Book: The Definitive, Fully Illu...",0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8361,The End of Evolution: On Mass Extinctions and ...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8362,In the Beginning: A Scientist Shows Why the Cr...,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8363,Browns Gde Survive Tr,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [432]:
vectorizer_df=vectorizer_df.drop(['Title'],axis=1)
vector_matrix=vectorizer_df.to_numpy()
vector_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [433]:
# Compute the Cosine Similarity matrix based on the vector_matrix
cosine_sim = cosine_similarity(vector_matrix, vector_matrix)

# Construct reverse mapping
indices = pd.Series(modified_books.index, index=modified_books['Title'])
indices

Title
Classical Mythology                                                                                                   0
Clara Callan                                                                                                          1
Decision in Normandy                                                                                                  2
Flu: The Story of the Great Influenza Pandemic of 1918 and the Search for the Virus That Caused It                    3
The Mummies of Urumchi                                                                                                4
                                                                                                                   ...
The Rodale Herb Book: How to Use, Grow, and Buy Nature's Miracle Plants (An Organic gardening and farming book)    8359
Dinosaur Data Book: The Definitive, Fully Illustrated Encyclopedia of Dinosaurs                                    8360
The End of Evolution: On Mass Extinctions and the Preservation of Biodiversity                                     8361
In the Beginning: A Scientist Shows Why the Creationists Are Wrong                                                 8362
Browns Gde Survive Tr                                                                                              8363
Length: 8025, dtype: int64

In [434]:
# Function that takes in book title as input and outputs most similar books based on the parameters assumed
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all books with that book
    sim_scores = list(enumerate(cosine_sim[idx]))
    #Enumerate() method adds a counter to an iterable and returns it in a form of enumerate object

    # Sort the books based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the books of the 10 most similar books
    sim_scores = sim_scores[1:11]

    # Get the books indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar books
    return modified_books['Title'].iloc[movie_indices]

In [435]:
#Get Similar books to the given input based on the parameters taken into account
get_recommendations('The Girl Who Loved Tom Gordon', cosine_sim)

1534                                       The Green Mile
1926                Everything's Eventual : 14 Dark Tales
2033                                   Hearts In Atlantis
4081                                         Bag of Bones
45                                     I'll Be Seeing You
60                                          LONESOME DOVE
95                              Pretend You Don't See Her
110     Bless The Beasts And Children : Bless The Beas...
162                  The Hitchhiker's Guide to the Galaxy
229                                          Pet Sematary
Name: Title, dtype: object