In [146]:
import pandas as pd 
import numpy as np
import pylab 
import seaborn as sns
import scipy.stats as st
import statsmodels.api as sm
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from sklearn.model_selection import train_test_split

computer=pd.read_csv("C:\\Users\\kp\\Pictures\\Assignments\\Multi Linear Regression\\Computer_Data.csv",header=0)

# # Scatter plot between the variables along with histograms
# sns.pairplot(computer)
# plt.show()

# # Scatter plot between the variables along with histograms using Pandas
# pd.plotting.scatter_matrix(computer,figsize=(20,15))
# plt.show()
computer

,Unnamed: 0,price,speed,hd,ram,screen,cd,multi,premium,ads,trend
0,1,1499,25,80,4,14,no,no,yes,94,1
1,2,1795,33,85,2,14,no,no,yes,94,1
2,3,1595,25,170,4,15,no,no,yes,94,1
3,4,1849,25,170,8,14,no,no,no,94,1
4,5,3295,33,340,16,14,no,no,yes,94,1
...,...,...,...,...,...,...,...,...,...,...,...
6254,6255,1690,100,528,8,15,no,no,yes,39,35
6255,6256,2223,66,850,16,15,yes,yes,yes,39,35
6256,6257,2654,100,1200,24,15,yes,no,yes,39,35
6257,6258,2195,100,850,16,15,yes,no,yes,39,35
6258,6259,2490,100,850,16,17,yes,no,yes,39,35

In [147]:
computer=pd.get_dummies(computer,columns=['cd','multi','premium'])
computer.drop(['Unnamed: 0'],axis=1,inplace=True)

#Dropping records which are too sensitive for the regressor to learn the pattern(Outliers) by Influencer Plot
computer.drop(computer.index[[5960,4477,3783,900,1101,1610,1524,2042,1835,1688,1700,720,1784,1440,1048,79]],axis=0,inplace=True)

features=['speed', 'hd', 'ram', 'screen', 'ads', 'trend', 'cd_yes', 'multi_yes', 'premium_yes']
target=['price']
computer

,price,speed,hd,ram,screen,ads,trend,cd_no,cd_yes,multi_no,multi_yes,premium_no,premium_yes
0,1499,25,80,4,14,94,1,1,0,1,0,0,1
1,1795,33,85,2,14,94,1,1,0,1,0,0,1
2,1595,25,170,4,15,94,1,1,0,1,0,0,1
3,1849,25,170,8,14,94,1,1,0,1,0,1,0
4,3295,33,340,16,14,94,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6254,1690,100,528,8,15,39,35,1,0,1,0,0,1
6255,2223,66,850,16,15,39,35,0,1,0,1,0,1
6256,2654,100,1200,24,15,39,35,0,1,1,0,0,1
6257,2195,100,850,16,15,39,35,0,1,1,0,0,1
6258,2490,100,850,16,17,39,35,0,1,1,0,0,1

In [148]:
### Splitting the data into train and test data 
train_data,test_data = train_test_split(computer,test_size = 0.2,random_state=42) # 20% size

In [149]:
#Model Building

regressor=smf.ols("price~speed+hd+ram+screen+ads+trend+cd_yes+multi_yes+premium_yes",data=train_data).fit()

#Summary
regressor.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.779
Model:                            OLS   Adj. R-squared:                  0.778
Method:                 Least Squares   F-statistic:                     1947.
Date:                Wed, 29 Apr 2020   Prob (F-statistic):               0.00
Time:                        19:30:26   Log-Likelihood:                -35093.
No. Observations:                4994   AIC:                         7.021e+04
Df Residuals:                    4984   BIC:                         7.027e+04
Df Model:                           9
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept     343.1628     66.251      5.180      0.000     213.282     473.044
speed           9.3640      0.205     45.663      0.000       8.962       9.766
hd              0.7704      0.033     23.092      0.000       0.705       0.836
ram            48.7776      1.239     39.355      0.000      46.348      51.207
screen        120.7587      4.383     27.553      0.000     112.166     129.351
ads             0.6596      0.058     11.461      0.000       0.547       0.772
trend         -51.4251      0.717    -71.729      0.000     -52.831     -50.020
cd_yes         63.2598     10.523      6.011      0.000      42.629      83.890
multi_yes     105.2958     12.655      8.321      0.000      80.487     130.105
premium_yes  -521.5584     13.656    -38.192      0.000    -548.331    -494.786
==============================================================================
Omnibus:                      662.057   Durbin-Watson:                   1.998
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1652.117
Skew:                           0.753   Prob(JB):                         0.00
Kurtosis:                       5.382   Cond. No.                     9.03e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.03e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [150]:
train_pred=regressor.predict(train_data[features])
test_pred=regressor.predict(test_data[features])
# sm.graphics.influence_plot(regressor)
# plt.show()

In [151]:
# #Normality Test for Residuals 
# #In Order to have a Model's good fit it is important to have the Residuals follow a Normal Distribution Pattern

# # Normal Distribution Check using Histogram
# plt.figure(figsize=(20,15))
# plt.hist(regressor.resid_pearson) 
# plt.show()

# # Normal Distribution Check using Q-Q plot
# plt.figure(figsize=(20,15))
# st.probplot(regressor.resid_pearson, dist="norm", plot=pylab) 
# plt.show()

In [152]:
# # Homoscedasticity : Error term being same across all values of independent variables
# # Fitted Values Vs Residuals
# plt.figure(figsize=(15,10))
# plt.scatter(train_pred,regressor.resid_pearson,c="r"),plt.axhline(y=0,color='blue');plt.xlabel("Fitted_Values");plt.ylabel("Residuals")

In [153]:
# Residual values 
train_residual  = train_pred - train_data['price']
test_residual  = test_pred - test_data['price']

# RMSE value for train and test Data
train_rmse = np.sqrt(np.mean(train_residual*train_residual))
test_rmse = np.sqrt(np.mean(test_residual*test_residual))

print("RMSE Value for the Train Dataset: ",train_rmse)
print("RMSE Value for the Test Dataset: ",test_rmse)

RMSE Value for the Train Dataset:  272.6081625687431
RMSE Value for the Test Dataset:  272.2112806774912